### ISSUE TITLE
compute input embeddings error: "no such file or directory"

### ISSUE THREAD

**Issue by nwesthoff** [googlecreativelab/open-nsynth-super#30]
running `$ python 01_compute_input_embeddings.py` from `~/open-nsynth-super/audio/workdir` to test the pipeline gives me an `OSError: [Errno 2] No such file or directory`

I split up the subprocess.call to get a more specific line, though I don't think that worked (it breaks on the last line regardless).

Traceback:
```
Traceback (most recent call last):
  File "01_compute_input_embeddings.py", line 31, in <module>
    subprocess.call(["nsynth_save_embeddings", "--checkpoint_path=%s/magenta/models/nsynth/wavenet-ckpt/model.ckpt-200000" % settings['magenta_dir'], "--source_path=%s/audio_input" % source_dir, "--batch_size=64", "--save_path=%s/embeddings_input" % source_dir])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
all folders exist and are readable, writeable and executable by current user

I think it might have to do something with the wavenet-ckpt folder which contains `checkpoint`, `model.ckpt-200000.data-00000-of-00001`, `model.ckpt-200000.index` and `model.ckpt-200000.meta` but no `model.ckpt-200000`

**Comment by nwesthoff** [comment]
Scratch that. I think it has trouble locating `nsynth_save_embeddings`, which is in `~/magenta/magenta/models/nsynth/wavenet`, not inside the workdir, is this incorrect on my part? or an error in the python script? I'm also not sure what the best way is to fix it.

**Comment by nwesthoff** [comment]
Reran the entire process of fetching and building magenta, that fixed it. I think that installed `nsynth_save_embeddings` as a general command.
