### ISSUE TITLE
05_clean_files.py fails with audioread.NoBackendError

### ISSUE THREAD

**Issue by 9600** [googlecreativelab/open-nsynth-super#53]
Run on a 2x GPU system with 4x instruments per corner. Completes fine with one batch and not the other. Guess the error is misleading...

@jesseengel, wondering if you've seen this? (and doesn't seem like anyone else is watching this repo!)

//

(magenta) andrew@blast:/data/Liles/nsynth/open-nsynth-super/audio/workdir$
(magenta) andrew@blast:/data/Liles/nsynth/open-nsynth-super/audio/workdir$ python 05_clean_files.py 1
Normalising input WAVs
  2%|█▊                                                                                                         | 992/57784 [03:26<3:16:57,  4.81it/s]100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 57784/57784 [3:24:43<00:00,  4.70it/s]
Converting to WAV
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 104431/104431 [41:26<00:00, 42.00it/s]
(magenta) andrew@blast:/data/Liles/nsynth/open-nsynth-super/audio/workdir$
(magenta) andrew@blast:/data/Liles/nsynth/open-nsynth-super/audio/workdir$
(magenta) andrew@blast:/data/Liles/nsynth/open-nsynth-super/audio/workdir$
(magenta) andrew@blast:/data/Liles/nsynth/open-nsynth-super/audio/workdir$
(magenta) andrew@blast:/data/Liles/nsynth/open-nsynth-super/audio/workdir$
(magenta) andrew@blast:/data/Liles/nsynth/open-nsynth-super/audio/workdir$ python 05_clean_files.py 0
Normalising input WAVs
 27%|█████████████████████████████▊                                                                                 | 15537/57784 [58:29<2:39:03,  4.43it/s]sox WARN gain: gain clipped 63999 samples; decrease volume?
sox WARN dither: dither clipped 56045 samples; decrease volume?
 28%|███████████████████████████████                                                                              | 16454/57784 [1:01:56<2:35:35,  4.43it/s]sox WARN gain: gain clipped 63902 samples; decrease volume?
sox WARN dither: dither clipped 56048 samples; decrease volume?
 70%|███████████████████████████████████████████████████████████████████████████▉                                 | 40228/57784 [2:31:36<1:06:09,  4.42it/s]sox WARN gain: gain clipped 64000 samples; decrease volume?
sox WARN dither: dither clipped 55997 samples; decrease volume?
 81%|█████████████████████████████████████████████████████████████████████████████████████████▌                     | 46647/57784 [2:55:49<41:58,  4.42it/s]Traceback (most recent call last):
  File "05_clean_files.py", line 46, in <module>
    audio, sr = librosa.core.load(os.path.join(original_path, fpath), sr=16000)
  File "/data/Liles/nsynth/miniconda2/envs/magenta/lib/python2.7/site-packages/librosa/core/audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/data/Liles/nsynth/miniconda2/envs/magenta/lib/python2.7/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError

**Comment by jesseengel** [comment]
Hey, Isn't this something you saw and fixed in #50?

I've seen this before as an upstream audioread/librosa issue (ex: https://github.com/librosa/librosa/issues/390, https://github.com/librosa/librosa/issues/589, https://github.com/librosa/librosa/issues/650).

**Comment by 9600** [comment]
@jesseengel looks like it's upstream. Was failing on just one file, which seems OK:

$ soxi gen_drone1_0.596_drone2_0.357_piano_0.047_pitch_48.wav

Input File     : 'gen_drone1_0.596_drone2_0.357_piano_0.047_pitch_48.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 24-bit
Duration       : 00:00:04.00 = 64000 samples ~ 300 CDDA sectors
File Size      : 256k
Bit Rate       : 512k
Sample Encoding: 32-bit Floating Point PCM

By modifying 05_clean_files.py so that it didn't just crash out and instead logged the error and continued, I could then bodge it by copying the neighbouring interpolation point WAV for those instruments and proceed to the next stage.
